/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedPetsRouteRouteImport } from './routes/_authenticated/pets/route'
import { Route as AuthenticatedHealthRouteRouteImport } from './routes/_authenticated/health/route'
import { Route as AuthenticatedPetsIndexRouteImport } from './routes/_authenticated/pets/index'
import { Route as AuthenticatedHealthIndexRouteImport } from './routes/_authenticated/health/index'
import { Route as AuthenticatedHealthVetRouteImport } from './routes/_authenticated/health/vet'
import { Route as AuthenticatedHealthVaccinationsRouteImport } from './routes/_authenticated/health/vaccinations'
import { Route as AuthenticatedHealthDewormingsRouteImport } from './routes/_authenticated/health/dewormings'
import { Route as AuthenticatedPetsPetIdRouteRouteImport } from './routes/_authenticated/pets/$petId/route'
import { Route as AuthenticatedPetsPetIdIndexRouteImport } from './routes/_authenticated/pets/$petId/index'
import { Route as AuthenticatedPetsPetIdVaccinationsRouteImport } from './routes/_authenticated/pets/$petId/vaccinations'
import { Route as AuthenticatedPetsPetIdDewormingsRouteImport } from './routes/_authenticated/pets/$petId/dewormings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsRouteRoute = AuthenticatedPetsRouteRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRouteRoute =
  AuthenticatedHealthRouteRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetsIndexRoute = AuthenticatedPetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPetsRouteRoute,
} as any)
const AuthenticatedHealthIndexRoute =
  AuthenticatedHealthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHealthRouteRoute,
  } as any)
const AuthenticatedHealthVetRoute = AuthenticatedHealthVetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => AuthenticatedHealthRouteRoute,
} as any)
const AuthenticatedHealthVaccinationsRoute =
  AuthenticatedHealthVaccinationsRouteImport.update({
    id: '/vaccinations',
    path: '/vaccinations',
    getParentRoute: () => AuthenticatedHealthRouteRoute,
  } as any)
const AuthenticatedHealthDewormingsRoute =
  AuthenticatedHealthDewormingsRouteImport.update({
    id: '/dewormings',
    path: '/dewormings',
    getParentRoute: () => AuthenticatedHealthRouteRoute,
  } as any)
const AuthenticatedPetsPetIdRouteRoute =
  AuthenticatedPetsPetIdRouteRouteImport.update({
    id: '/$petId',
    path: '/$petId',
    getParentRoute: () => AuthenticatedPetsRouteRoute,
  } as any)
const AuthenticatedPetsPetIdIndexRoute =
  AuthenticatedPetsPetIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPetsPetIdRouteRoute,
  } as any)
const AuthenticatedPetsPetIdVaccinationsRoute =
  AuthenticatedPetsPetIdVaccinationsRouteImport.update({
    id: '/vaccinations',
    path: '/vaccinations',
    getParentRoute: () => AuthenticatedPetsPetIdRouteRoute,
  } as any)
const AuthenticatedPetsPetIdDewormingsRoute =
  AuthenticatedPetsPetIdDewormingsRouteImport.update({
    id: '/dewormings',
    path: '/dewormings',
    getParentRoute: () => AuthenticatedPetsPetIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/health': typeof AuthenticatedHealthRouteRouteWithChildren
  '/pets': typeof AuthenticatedPetsRouteRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/pets/$petId': typeof AuthenticatedPetsPetIdRouteRouteWithChildren
  '/health/dewormings': typeof AuthenticatedHealthDewormingsRoute
  '/health/vaccinations': typeof AuthenticatedHealthVaccinationsRoute
  '/health/vet': typeof AuthenticatedHealthVetRoute
  '/health/': typeof AuthenticatedHealthIndexRoute
  '/pets/': typeof AuthenticatedPetsIndexRoute
  '/pets/$petId/dewormings': typeof AuthenticatedPetsPetIdDewormingsRoute
  '/pets/$petId/vaccinations': typeof AuthenticatedPetsPetIdVaccinationsRoute
  '/pets/$petId/': typeof AuthenticatedPetsPetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/health/dewormings': typeof AuthenticatedHealthDewormingsRoute
  '/health/vaccinations': typeof AuthenticatedHealthVaccinationsRoute
  '/health/vet': typeof AuthenticatedHealthVetRoute
  '/health': typeof AuthenticatedHealthIndexRoute
  '/pets': typeof AuthenticatedPetsIndexRoute
  '/pets/$petId/dewormings': typeof AuthenticatedPetsPetIdDewormingsRoute
  '/pets/$petId/vaccinations': typeof AuthenticatedPetsPetIdVaccinationsRoute
  '/pets/$petId': typeof AuthenticatedPetsPetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/health': typeof AuthenticatedHealthRouteRouteWithChildren
  '/_authenticated/pets': typeof AuthenticatedPetsRouteRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/pets/$petId': typeof AuthenticatedPetsPetIdRouteRouteWithChildren
  '/_authenticated/health/dewormings': typeof AuthenticatedHealthDewormingsRoute
  '/_authenticated/health/vaccinations': typeof AuthenticatedHealthVaccinationsRoute
  '/_authenticated/health/vet': typeof AuthenticatedHealthVetRoute
  '/_authenticated/health/': typeof AuthenticatedHealthIndexRoute
  '/_authenticated/pets/': typeof AuthenticatedPetsIndexRoute
  '/_authenticated/pets/$petId/dewormings': typeof AuthenticatedPetsPetIdDewormingsRoute
  '/_authenticated/pets/$petId/vaccinations': typeof AuthenticatedPetsPetIdVaccinationsRoute
  '/_authenticated/pets/$petId/': typeof AuthenticatedPetsPetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/health'
    | '/pets'
    | '/activity'
    | '/home'
    | '/profile'
    | '/schedule'
    | '/pets/$petId'
    | '/health/dewormings'
    | '/health/vaccinations'
    | '/health/vet'
    | '/health/'
    | '/pets/'
    | '/pets/$petId/dewormings'
    | '/pets/$petId/vaccinations'
    | '/pets/$petId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/activity'
    | '/home'
    | '/profile'
    | '/schedule'
    | '/health/dewormings'
    | '/health/vaccinations'
    | '/health/vet'
    | '/health'
    | '/pets'
    | '/pets/$petId/dewormings'
    | '/pets/$petId/vaccinations'
    | '/pets/$petId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/health'
    | '/_authenticated/pets'
    | '/_authenticated/activity'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/_authenticated/pets/$petId'
    | '/_authenticated/health/dewormings'
    | '/_authenticated/health/vaccinations'
    | '/_authenticated/health/vet'
    | '/_authenticated/health/'
    | '/_authenticated/pets/'
    | '/_authenticated/pets/$petId/dewormings'
    | '/_authenticated/pets/$petId/vaccinations'
    | '/_authenticated/pets/$petId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets': {
      id: '/_authenticated/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AuthenticatedPetsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets/': {
      id: '/_authenticated/pets/'
      path: '/'
      fullPath: '/pets/'
      preLoaderRoute: typeof AuthenticatedPetsIndexRouteImport
      parentRoute: typeof AuthenticatedPetsRouteRoute
    }
    '/_authenticated/health/': {
      id: '/_authenticated/health/'
      path: '/'
      fullPath: '/health/'
      preLoaderRoute: typeof AuthenticatedHealthIndexRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
    '/_authenticated/health/vet': {
      id: '/_authenticated/health/vet'
      path: '/vet'
      fullPath: '/health/vet'
      preLoaderRoute: typeof AuthenticatedHealthVetRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
    '/_authenticated/health/vaccinations': {
      id: '/_authenticated/health/vaccinations'
      path: '/vaccinations'
      fullPath: '/health/vaccinations'
      preLoaderRoute: typeof AuthenticatedHealthVaccinationsRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
    '/_authenticated/health/dewormings': {
      id: '/_authenticated/health/dewormings'
      path: '/dewormings'
      fullPath: '/health/dewormings'
      preLoaderRoute: typeof AuthenticatedHealthDewormingsRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
    '/_authenticated/pets/$petId': {
      id: '/_authenticated/pets/$petId'
      path: '/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof AuthenticatedPetsPetIdRouteRouteImport
      parentRoute: typeof AuthenticatedPetsRouteRoute
    }
    '/_authenticated/pets/$petId/': {
      id: '/_authenticated/pets/$petId/'
      path: '/'
      fullPath: '/pets/$petId/'
      preLoaderRoute: typeof AuthenticatedPetsPetIdIndexRouteImport
      parentRoute: typeof AuthenticatedPetsPetIdRouteRoute
    }
    '/_authenticated/pets/$petId/vaccinations': {
      id: '/_authenticated/pets/$petId/vaccinations'
      path: '/vaccinations'
      fullPath: '/pets/$petId/vaccinations'
      preLoaderRoute: typeof AuthenticatedPetsPetIdVaccinationsRouteImport
      parentRoute: typeof AuthenticatedPetsPetIdRouteRoute
    }
    '/_authenticated/pets/$petId/dewormings': {
      id: '/_authenticated/pets/$petId/dewormings'
      path: '/dewormings'
      fullPath: '/pets/$petId/dewormings'
      preLoaderRoute: typeof AuthenticatedPetsPetIdDewormingsRouteImport
      parentRoute: typeof AuthenticatedPetsPetIdRouteRoute
    }
  }
}

interface AuthenticatedHealthRouteRouteChildren {
  AuthenticatedHealthDewormingsRoute: typeof AuthenticatedHealthDewormingsRoute
  AuthenticatedHealthVaccinationsRoute: typeof AuthenticatedHealthVaccinationsRoute
  AuthenticatedHealthVetRoute: typeof AuthenticatedHealthVetRoute
  AuthenticatedHealthIndexRoute: typeof AuthenticatedHealthIndexRoute
}

const AuthenticatedHealthRouteRouteChildren: AuthenticatedHealthRouteRouteChildren =
  {
    AuthenticatedHealthDewormingsRoute: AuthenticatedHealthDewormingsRoute,
    AuthenticatedHealthVaccinationsRoute: AuthenticatedHealthVaccinationsRoute,
    AuthenticatedHealthVetRoute: AuthenticatedHealthVetRoute,
    AuthenticatedHealthIndexRoute: AuthenticatedHealthIndexRoute,
  }

const AuthenticatedHealthRouteRouteWithChildren =
  AuthenticatedHealthRouteRoute._addFileChildren(
    AuthenticatedHealthRouteRouteChildren,
  )

interface AuthenticatedPetsPetIdRouteRouteChildren {
  AuthenticatedPetsPetIdDewormingsRoute: typeof AuthenticatedPetsPetIdDewormingsRoute
  AuthenticatedPetsPetIdVaccinationsRoute: typeof AuthenticatedPetsPetIdVaccinationsRoute
  AuthenticatedPetsPetIdIndexRoute: typeof AuthenticatedPetsPetIdIndexRoute
}

const AuthenticatedPetsPetIdRouteRouteChildren: AuthenticatedPetsPetIdRouteRouteChildren =
  {
    AuthenticatedPetsPetIdDewormingsRoute:
      AuthenticatedPetsPetIdDewormingsRoute,
    AuthenticatedPetsPetIdVaccinationsRoute:
      AuthenticatedPetsPetIdVaccinationsRoute,
    AuthenticatedPetsPetIdIndexRoute: AuthenticatedPetsPetIdIndexRoute,
  }

const AuthenticatedPetsPetIdRouteRouteWithChildren =
  AuthenticatedPetsPetIdRouteRoute._addFileChildren(
    AuthenticatedPetsPetIdRouteRouteChildren,
  )

interface AuthenticatedPetsRouteRouteChildren {
  AuthenticatedPetsPetIdRouteRoute: typeof AuthenticatedPetsPetIdRouteRouteWithChildren
  AuthenticatedPetsIndexRoute: typeof AuthenticatedPetsIndexRoute
}

const AuthenticatedPetsRouteRouteChildren: AuthenticatedPetsRouteRouteChildren =
  {
    AuthenticatedPetsPetIdRouteRoute:
      AuthenticatedPetsPetIdRouteRouteWithChildren,
    AuthenticatedPetsIndexRoute: AuthenticatedPetsIndexRoute,
  }

const AuthenticatedPetsRouteRouteWithChildren =
  AuthenticatedPetsRouteRoute._addFileChildren(
    AuthenticatedPetsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHealthRouteRoute: typeof AuthenticatedHealthRouteRouteWithChildren
  AuthenticatedPetsRouteRoute: typeof AuthenticatedPetsRouteRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHealthRouteRoute: AuthenticatedHealthRouteRouteWithChildren,
  AuthenticatedPetsRouteRoute: AuthenticatedPetsRouteRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
