/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPetsRouteImport } from './routes/_authenticated/pets'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedHealthRouteRouteImport } from './routes/_authenticated/health/route'
import { Route as AuthenticatedHealthIndexRouteImport } from './routes/_authenticated/health/index'
import { Route as AuthenticatedHealthVetRouteImport } from './routes/_authenticated/health/vet'
import { Route as AuthenticatedHealthVaccinationsRouteImport } from './routes/_authenticated/health/vaccinations'
import { Route as AuthenticatedHealthDewormingRouteImport } from './routes/_authenticated/health/deworming'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsRoute = AuthenticatedPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRouteRoute =
  AuthenticatedHealthRouteRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthIndexRoute =
  AuthenticatedHealthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHealthRouteRoute,
  } as any)
const AuthenticatedHealthVetRoute = AuthenticatedHealthVetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => AuthenticatedHealthRouteRoute,
} as any)
const AuthenticatedHealthVaccinationsRoute =
  AuthenticatedHealthVaccinationsRouteImport.update({
    id: '/vaccinations',
    path: '/vaccinations',
    getParentRoute: () => AuthenticatedHealthRouteRoute,
  } as any)
const AuthenticatedHealthDewormingRoute =
  AuthenticatedHealthDewormingRouteImport.update({
    id: '/deworming',
    path: '/deworming',
    getParentRoute: () => AuthenticatedHealthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/health': typeof AuthenticatedHealthRouteRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/health/deworming': typeof AuthenticatedHealthDewormingRoute
  '/health/vaccinations': typeof AuthenticatedHealthVaccinationsRoute
  '/health/vet': typeof AuthenticatedHealthVetRoute
  '/health/': typeof AuthenticatedHealthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/home': typeof AuthenticatedHomeRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/health/deworming': typeof AuthenticatedHealthDewormingRoute
  '/health/vaccinations': typeof AuthenticatedHealthVaccinationsRoute
  '/health/vet': typeof AuthenticatedHealthVetRoute
  '/health': typeof AuthenticatedHealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/health': typeof AuthenticatedHealthRouteRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/pets': typeof AuthenticatedPetsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/health/deworming': typeof AuthenticatedHealthDewormingRoute
  '/_authenticated/health/vaccinations': typeof AuthenticatedHealthVaccinationsRoute
  '/_authenticated/health/vet': typeof AuthenticatedHealthVetRoute
  '/_authenticated/health/': typeof AuthenticatedHealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/health'
    | '/activity'
    | '/home'
    | '/pets'
    | '/profile'
    | '/schedule'
    | '/health/deworming'
    | '/health/vaccinations'
    | '/health/vet'
    | '/health/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/activity'
    | '/home'
    | '/pets'
    | '/profile'
    | '/schedule'
    | '/health/deworming'
    | '/health/vaccinations'
    | '/health/vet'
    | '/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/health'
    | '/_authenticated/activity'
    | '/_authenticated/home'
    | '/_authenticated/pets'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/_authenticated/health/deworming'
    | '/_authenticated/health/vaccinations'
    | '/_authenticated/health/vet'
    | '/_authenticated/health/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets': {
      id: '/_authenticated/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AuthenticatedPetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health/': {
      id: '/_authenticated/health/'
      path: '/'
      fullPath: '/health/'
      preLoaderRoute: typeof AuthenticatedHealthIndexRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
    '/_authenticated/health/vet': {
      id: '/_authenticated/health/vet'
      path: '/vet'
      fullPath: '/health/vet'
      preLoaderRoute: typeof AuthenticatedHealthVetRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
    '/_authenticated/health/vaccinations': {
      id: '/_authenticated/health/vaccinations'
      path: '/vaccinations'
      fullPath: '/health/vaccinations'
      preLoaderRoute: typeof AuthenticatedHealthVaccinationsRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
    '/_authenticated/health/deworming': {
      id: '/_authenticated/health/deworming'
      path: '/deworming'
      fullPath: '/health/deworming'
      preLoaderRoute: typeof AuthenticatedHealthDewormingRouteImport
      parentRoute: typeof AuthenticatedHealthRouteRoute
    }
  }
}

interface AuthenticatedHealthRouteRouteChildren {
  AuthenticatedHealthDewormingRoute: typeof AuthenticatedHealthDewormingRoute
  AuthenticatedHealthVaccinationsRoute: typeof AuthenticatedHealthVaccinationsRoute
  AuthenticatedHealthVetRoute: typeof AuthenticatedHealthVetRoute
  AuthenticatedHealthIndexRoute: typeof AuthenticatedHealthIndexRoute
}

const AuthenticatedHealthRouteRouteChildren: AuthenticatedHealthRouteRouteChildren =
  {
    AuthenticatedHealthDewormingRoute: AuthenticatedHealthDewormingRoute,
    AuthenticatedHealthVaccinationsRoute: AuthenticatedHealthVaccinationsRoute,
    AuthenticatedHealthVetRoute: AuthenticatedHealthVetRoute,
    AuthenticatedHealthIndexRoute: AuthenticatedHealthIndexRoute,
  }

const AuthenticatedHealthRouteRouteWithChildren =
  AuthenticatedHealthRouteRoute._addFileChildren(
    AuthenticatedHealthRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHealthRouteRoute: typeof AuthenticatedHealthRouteRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPetsRoute: typeof AuthenticatedPetsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHealthRouteRoute: AuthenticatedHealthRouteRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPetsRoute: AuthenticatedPetsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
